notifications:
  email:
    recipients:
      - pascal.knodel@student.kit.edu
      - tobias.schulz186@gmail.com
    on_success: change
    on_failure: always
language: c
install:
  - sudo apt-get install mono-devel mono-dmcs nunit-console
before_install:
  - wget https://github.com/pse-knot/MonoGame/releases/download/v3.1.2/MonoGame-Linux-20130126.zip
  - mkdir -p Knot3/bin/Debug/
  - unzip -d Knot3/bin/Debug/ MonoGame-Linux-20130126.zip
script:
  - xbuild Knot3-Prototyp-Linux.sln
